=== Laxman-creator/EdYou_automation_project/target/test-classes/resources/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="encoding" type="xs:string" />
				<xs:element name="protocol" type="xs:string" />
				<xs:element name="title" type="xs:string" />
				<xs:element name="reportName" type="xs:string" />
				<xs:element name="theme" type="xs:string" />
				<xs:element name="testViewChartLocation" type="xs:string" />
				<xs:element name="chartsVisibilityOnOpen" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Laxman-creator/EdYou_automation_project/src/test/java/resources/config.xml
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="config.xsd">
        <encoding>UTF-8</encoding>
        <protocol>HTTPS</protocol>
        <title>Automation Report</title>
        <reportName>Extent Report</reportName>
        <theme>dark</theme>
        <testViewChartLocation>top</testViewChartLocation>
        <chartsVisibilityOnOpen>true</chartsVisibilityOnOpen>
    </configuration>
